In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
print(len(arr))

5


In [ ]:
print(arr.shape)

(5,)


Numpy gives us a way to add a number to all the available values with one line.

In [ ]:
arr+10

array([11, 12, 13, 14, 15])

In python we can append to a list.
```python
a = [1,2,3]
a.append(4)
print(a) #output: [1,2,3,4]
```
But Numpy doesn't support that!

In [ ]:
arr.append(6.3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
narr = np.delete(arr,3)

In [ ]:
arr = arr.sort()

In [ ]:
narr = np.array([[1,2,3],[3,4,5]])
print(narr.shape)
print(narr.ndim)

(2, 3)
2


Indexing and slicing same as regular python

# Printing Columns and Rows

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[:,0])
print(arr[0,:])

[1 4]
[1 2 3]


In [ ]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [ ]:
y = np.zeros((5,2))
print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
z = np.ones(4)
print(z)

[1. 1. 1. 1.]


In [ ]:
x = np.zeros(3, dtype=int)
x

array([0, 0, 0])

In [ ]:
print(np.sum(arr))
print(np.prod(arr))
b = np.array([[1,2,3],[4,5,6]])
print(np.sum(b, axis = 0)) #column wise calc
print(np.sum(b, axis=1)) # row wise calc

21
720
[5 7 9]
[ 6 15]


## Logical Indexing

In [ ]:
print(b>2)

[[False False  True]
 [ True  True  True]]


In [ ]:
b[b>2] = 100
b

array([[  1,   2, 100],
       [100, 100, 100]])

# Iteration
Just like normal python

## Linspace
Gives us an array that will give us equally spaced values within a range.
np.linspace(start, end, values, dtype = if needed specific type)

In [ ]:
x = np.linspace(0,100,5)
x

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
x = np.linspace(0,100,5, dtype=int)
x

array([  0,  25,  50,  75, 100])

# Pandas

In [ ]:
import pandas as pd

## Dataframe

In [ ]:
data = {
    "name":["Alif", "Samira"],
    "Age": [22,22]
}

df = pd.DataFrame(data)
df

name  Age
0    Alif   22
1  Samira   22